## Take home exercises

Numpy Questions

  1. Define two custom numpy arrays, say A and B. Generate two new numpy
  arrays by stacking A and B vertically and horizontally.
  2. Find common elements between A and B. [Hint : Intersection of two sets]
  3. Extract all numbers from A which are within a specific range. eg
  between 5 and 10. [Hint: np.where() might be useful or boolean masks]
  4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5
  and sepallength (1st column) < 5.0
  url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
  iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Pandas Questions
1. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```
2. Replace missing values in Min.Price and Max.Price columns with
their respective mean.
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```
3. How to get the rows of a dataframe with row sum > 100?
```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))


In [1]:
import numpy as np
import pandas as pd

In [2]:
A = np.array([[10, 12, 3], [4, 8, 6]])
B = np.array([[7, 12, 9], [10, 11, 12]])

In [3]:
# Stack vertically
vertical_stack = np.vstack((A, B))
print("Vertical Stack:\n", vertical_stack)

horizontal_stack = np.hstack((A, B))
print("Horizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[10 12  3]
 [ 4  8  6]
 [ 7 12  9]
 [10 11 12]]
Horizontal Stack:
 [[10 12  3  7 12  9]
 [ 4  8  6 10 11 12]]


In [4]:
# 2. Finding common elements between A and B.
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: [10 12]


In [5]:
# 3. Extract all numbers from A which are within a specific range. eg between 5 and 10.
range_elements = A[(A >= 5) & (A <= 10)]
print("Elements in A between 5 and 10:", range_elements)

Elements in A between 5 and 10: [10  8  6]


In [6]:
# 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Iris Rows:\n", filtered_iris)

Filtered Iris Rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Pandas Question 

In [7]:
# 5. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
every_20th_row = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print("Every 20th row:\n", every_20th_row)

Every 20th row:
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [8]:
# 6. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print("After replacing missing values:")
print(df[['Min.Price', 'Max.Price']].head())


After replacing missing values:
   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


/var/folders/p9/vr_bj_hd2tl8js62dy5tc5fc0000gn/T/ipykernel_18773/3658150691.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
/var/folders/p9/vr_bj_hd2tl8js62dy5tc5fc0000gn/T/ipykernel_18773/3658150691.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting

In [9]:
# 7. How to get the rows of a dataframe with row sum > 100?
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
row_sum_gt_100 = df_random[df_random.sum(axis=1) > 100]
print("Rows with sum > 100:\n", row_sum_gt_100)

Rows with sum > 100:
      0   1   2   3
0   23  27  31  23
1   24  34  29  21
5   33  13  23  32
7   23  23  38  31
8   31  16  29  39
10  30  32  21  28
11  34  33  36  39
13  35  19  22  25
14  14  32  29  27
